### ISSUE TITLE
Config Versioning

### ISSUE THREAD

**Issue by ecsalomon** [medic/cht-conf#304]
For many analytics purposes, it is useful (or essential) to know what logic was active when a CHW took an action. For example, when forms change, the field schema may change or the correct way to calculate a metric may need to be updates. For tasks generated from predictive algorithms, it is important know what version of the rules.nools.js was used. 

It would be awesome to version components of a config  upon deployment and to record these somewhere. For example, form versions could be recorded in reports. Task logic could be versioned in task documents, perhaps?

**Comment by garethbowen** [comment]
FYI the version of each form is stored in the [user telemetry](https://github.com/medic/medic-docs/blob/a4f507cb16b89f8532af481a8255a83d7d99dc9b/user/telemetry.md#metadata). We could easily add the version of the "settings" doc as well. Would a monthly granularity suffice or do you need it more often?

One downside of documenting the task login the task documents is there could be unnecessary doc updates where the only thing that's changed is the settings version.

**Comment by ecsalomon** [comment]
For analytics, monthly granularity on settings updates might be insufficient. What about 1 doc per month per settings version, storing the start and end time of each telemetry doc? That way, we would get a close enough timestamp of the settings update and could also compare performance stats between versions?

**Comment by garethbowen** [comment]
Makes sense. Could be done at the same time as #5977

**Comment by mrsarm** [comment]
Due that we already implemented daily telemetry for the upcoming version (cht-core#6915), and we do store the version of forms used on each report sent, do we still need to implement something for this requirement?

@garethbowen

**Comment by garethbowen** [comment]
I think so, though it's potentially lower priority now. Having the form version is good, but I think we also need the settings version to be accurate. For example, if the task configuration is changed, we want to be able to the rate of task completion before and after the change. At the moment we could approximate that, but because we don't know when the settings doc was replicated to the device, we won't know for sure which tasks were completed using which version of the configuration.

Possibly we only need to store the settings version on the tasks doc, but we should ask around and make sure we cover all the relevant use cases.

There is a [similar discussion here](https://github.com/medic/medic-conf/issues/395).

**Comment by njogz** [comment]
Ready for AT on `304-config-versioning`

**Comment by ngaruko** [comment]
LGTM.
Setting version saved in telemetry.
```
  
      },
      "settings": "2-003c8e03a7ddce0d9803d89dc10c064f"
    }
 
```
and upon changing settings (just one permission changed in this case) and sync the telemetry:
```
 },
      "settings": "3-0f39990969064d6482e1269d5dd2826d"
    }
```
Feel free to merge @njogz
