### ISSUE TITLE
Translation validation fails on empty constant

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-conf#455]
**Describe the bug**
Providing an empty or whitespace value for a constant for a translation value in a properties file throws an error.

**To Reproduce**
1. Edit your configurations `messages-ne.properties`
2. Add a translation for `contact.primary_contact_name = सम्पर्क व्यक्ति: {{name || ' '}}`
3. Execute `update-custom-translations`

**Expected behavior**
No error - it's valid to have `''` or `' '` as values.

**Logs**
```
ERROR Cannot compile 'ne' translation with key 'contact.primary_contact_name' has placeholders that do not match any in the base translation provided 
```

**Environment**
- Instance: N/A
- Client platform: Linux
- cht-conf version: latest
- cht-core version: N/A

**Additional context**
Instead of using `{{name || ' '}}` in most cases using `{{name}}` is equivalent.

**Comment by ngaruko** [comment]
LGTM.
Tested on local with the branch following the description above:
Before
![image](https://user-images.githubusercontent.com/6979995/146285272-1aff293b-36c2-4a53-a932-f0b0348792ab.png)

After
![image](https://user-images.githubusercontent.com/6979995/146285409-558d92c7-372d-46bc-9268-747c4b35cd7f.png)
 Back to you @garethbowen -( there are conflicts in the PR; otherwise ready to merge)

**Comment by garethbowen** [comment]
Conflicts resolved and merged to master. Thanks!
