### ISSUE TITLE
Should have non-zero exit code when deployments are not successful

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-conf#458]
**Describe the bug**
cht-conf is used in automation like this [deploy-with-medic-conf](https://github.com/medic/cht-core/tree/master/.github/actions/deploy-with-medic-conf) action. The process' return code is the signal to GitHub actions

**To Reproduce**
A deployment in GitHub actions failed with error: 

> ERROR Failed to get a response from ***.gov.np//. Maybe you entered the wrong URL, wrong port or the instance is not started? Please check and try again.

https://github.com/medic/config-nssd/runs/4466030521?check_suite_focus=true

![Screenshot from 2021-12-09 07-11-06](https://user-images.githubusercontent.com/9014751/145422300-dcc73783-c43e-4cb5-a86d-94cb3a9d9b53.png)

**Expected behavior**
Expected: GitHub Actions should show this deployment as failing
Observed: Passing

**Additional context**
https://github.com/medic/app-services-team/issues/239

**Comment by ngaruko** [comment]
Still in the middle of testing - having trouble replicating this (master seem to throw errors when the url is invalid).
However, while we are here there seems be other errors not handled, for example, I tried to use `upload-custom-translation` without a translation folder (on a branch from `458-exit-codes` branch). The [build passed](https://github.com/medic/cht-conf/runs/4711292457?check_suite_focus=true) with a warning in the logs (![image](https://user-images.githubusercontent.com/6979995/148170939-00f22c5e-f97d-4b28-bfaf-453f6608dadb.png)

Did you want to have a look at this (and other actions) before we continue? @kennsippell

**Comment by kennsippell** [comment]
Hey @ngaruko . That `upload-custom-translation` issue appears to be a warning and not an error, so it doesn't stop the run or halt the cht-conf process like some of the other scenarios in this issue.  My opinion is that warning is the correct behaviour here since custom translations are optional and the action is included in the default actions (eg. `cht --local`).  Believe we can leave that as-is.

**Comment by ngaruko** [comment]
@kennsippell Thanks for the clarification. One thing to notice is that in the above case (where the command emits a warning, the `url` check is not done, in other words, it still pass the build even when the server is invalid). 
![image](https://user-images.githubusercontent.com/6979995/148307872-86509496-addc-49de-a380-0eea37f8cd0b.png)
Maybe something to look at later since most probably this is not the way the tool is being used in real life (ie I had to modify `cht-core/yml` to only use a specific action, [bypassing other actions](https://github.com/medic/cht-core/blob/458-test-conf/.github/actions/deploy-with-medic-conf/action.yml#L30) which would undoubtedly catch this but other than that, I tested a few other scenarios and it is looks good: 
![image](https://user-images.githubusercontent.com/6979995/148307517-bc6a0411-cb42-4be5-ac17-31940456d0c2.png)
