### ISSUE TITLE
Add watch mode

### ISSUE THREAD

**Issue by freddieptf** [medic/cht-conf#477]
**Is your feature request related to a problem? Please describe.**
App developers spend quite some time context switching between developing and running cht-conf commands to update their test instances with their changes

**Describe the solution you'd like**
A way to automate running cht-conf commands in realtime when building apps

**Comment by dianabarsan** [comment]
This is ready for AT on `freddieptf:watch_mode`.

**Comment by ngaruko** [comment]
Features tested

1. Changing app-settings 
<img width="1061" alt="image" src="https://user-images.githubusercontent.com/6979995/162639490-578908cb-d445-4396-b4e2-e584af596613.png">

2. edit forms
<img width="935" alt="image" src="https://user-images.githubusercontent.com/6979995/162639548-22434f97-c341-4f9c-824f-278eb4f5d549.png">

3. delete form
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/6979995/162639588-33b9a2fb-5740-45e5-98f8-d04202622b5b.png">
(Not sure why these warnings about other forms @freddieptf , but I guess since they are just warning, it is not a biggie?)
4. edit translations >
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/6979995/162639786-1aa589de-87ef-4dc3-acd1-42e7833f84c5.png">
>>new translation >
<img width="833" alt="image" src="https://user-images.githubusercontent.com/6979995/162639875-c91fa3e0-53bd-4e43-b0e5-b47ffd94f2ce.png">


6. resources : delete / edit / add ==> **_no changes_**
<img width="485" alt="image" src="https://user-images.githubusercontent.com/6979995/162639685-9f673ee5-020b-4ec3-a482-65659fc45fb6.png">


6. js files 
<img width="967" alt="image" src="https://user-images.githubusercontent.com/6979995/162640010-6aefc73d-3607-4257-b34d-a44e586e2b74.png">

**Comment by freddieptf** [comment]
@ngaruko For delete form, that's definitely a bug. The warning should only list form files (.xml, .properties.json, .xlsx) related to the one you're deleting. Let me investigate the resources scenarios and get back to you

**Comment by freddieptf** [comment]
@ngaruko pushed a fix for the delete form bug and tested resources delete/edit/add on the same project and was working as expected

**Comment by ngaruko** [comment]
Thanks @freddieptf Looks good now. Only deleted form is flagged 
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/6979995/163126174-f2c5d38a-ef6a-4802-9a33-db5dfe36ed78.png">
