### ISSUE TITLE
Error when invalid xPath paths in form

### ISSUE THREAD

**Issue by jkuester** [medic/cht-conf#479]
Currently, if you manually specify an [xPath path](https://docs.getodk.org/form-logic/#advanced-xpath-paths) in your XLSForm (instead of the `${...}` variable notation) there is no validation that the path is valid (that it points to a real field). There is no error at runtime, either, but the behavior has slightly changed in the newer versions of Enketo. Previously an invalid xPath path considered equal to the empty string. Now it is not.  Either way, it would be really nice to detect these invalid xPath paths and throw an error. It would make it a lot easier for app-developers to debug issues and maintain form integrity.

I believe an xPath that points to a non-existent node is technically "valid" according to the xPath spec.  Generally speaking, xPath expressions are just queries that may or may not have results. However, if we limit our validation to just "simple" xPath expressions that only describe a path (either relative to a node or absolute), then any of these expressions that do not have a result would be almost certainly a bug. We probably should not check xPath expressions that allow searching anywhere through the doc (they start with `//`) or expressions have predicates (inside square brackets: e.g. `/bookstore/book[category='children']/author`). [Here](https://github.com/jkuester/cht-upgrade-helper/blob/fa190eb41cbd5f1302f79e0ecc6d435fcc760534/src/lib/invalid-xpaths.js#L3) is a sample regex expression that should be able to select these "simple" xPath expressions.

**Comment by ngaruko** [comment]
Checked with latest `cht-conf` version:

1. run `validate-contact-form` with valid forms and see all pass:
<img width="693" alt="image" src="https://user-images.githubusercontent.com/6979995/180902043-233a34ca-6365-4492-ab63-badfdc6284ea.png">

2. Modify[ one of the forms](https://github.com/medic/cht-core/blob/master/config/default/forms/contact/clinic-edit.xml#L342) to include an invalid xpath and run `validate-contact-form` again, and see errors
<img width="1269" alt="image" src="https://user-images.githubusercontent.com/6979995/180901859-ba313dc9-f639-456e-9993-16b9a87ea9d6.png">

Question though @jkuester . There is a warning that `Some validations have been skipped because they require a CHT instance`. Do some of the form validations require `cht`?

**Comment by jkuester** [comment]
@ngaruko, yes we have an [existing validation](https://github.com/medic/cht-conf/blob/main/src/lib/validation/form/can-generate-xform.js) that checks to see the form xml can be successfully transformed into the Enekto HTML. That transformation happens within the `api` server. So that validation will try to call the server and make sure the transformation works before actually uploading the form.  If you run the `validate-*-forms` actions without providing a server connection (e.g. `--local`, --url...`, etc) then it will still try to run all the validations that do not require a server connection.
