### ISSUE TITLE
Error on notes that are set to required and have appearance of countdown-timer

### ISSUE THREAD

**Issue by freddieptf** [medic/cht-conf#508]
**Describe the bug**
cht-conf errors when converting forms with notes that have required set to `yes` and appearance set to `countdown-timer`. https://docs.communityhealthtoolkit.org/apps/reference/forms/app/#cht-xform-widgets

**Expected behavior**
No errors on required countdown-timer note widgets

**Comment by garethbowen** [comment]
@jkuester Is this because Notes cannot be "required" any more? Is there another way to do countdown timers?

**Comment by jkuester** [comment]
@garethbowen yes that validation is what is causing the cht-conf error.  If I recall correctly, I could not find any affect that setting `required` had on the `countdown-timer` note fields.  (It did not force the timer to be run.)  However, in the newer version of Enketo (coming with `4.0`) a required `countdown-timer` will prevent the form from advancing to the next page (because of how the new Enketo treats required notes).  We added some xslt magic to cht-core that will automatically remove the `required` from all note fields (including `countdown-timer` fields) when they are uploaded, but we also [added some validation](https://github.com/medic/cht-conf/issues/494) to cht-conf to prompt people to fix their form config.

If we actually wanted to support required `countdown-timer`'s (in a meaningful way such that the user has to let them run) this would be a new feature request that would require some level of code changes to the `countdown-widget` in order to support it....

**Comment by jkuester** [comment]
We actually now (as of cht-core `4.7.0`) have proper support for requiring `countdown-timer`s!  https://github.com/medic/cht-core/issues/8681

https://docs.communityhealthtoolkit.org/building/reference/forms/app/#countdown-timer
