### ISSUE TITLE
compile-app-settings action without instance displays error

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-conf#524]
**Describe the bug**
Attempting to only compile-app-settings (no other action) results in an error saying that an instance is required.

**To Reproduce**
1. Run `npx cht compile-app-settings`

**Observed behavior**
`ERROR Require exactly one of these parameter: --local --instance --url --archive`
It then seems to compile successfully after the error

**Expected behavior**
An instance should not be required to compile-app-settings 

**Logs**
If applicable, include the cht-conf output, server logs, and/or browser logs.

**Environment**
cht-conf 3.15.2 (latest)

**Comment by kennsippell** [comment]
Thanks for the review @jkuester.  Can you clarify next steps for me? I haven't made cht contributions in long enough that I'd benefit from a refresher or link to the process. 

Can I merge? Do I get a QA person? etc

**Comment by kennsippell** [comment]
Ready for AT on `524-no-help-for-actions-without-instance`

**Comment by jkuester** [comment]
@kennsippell sorry for the delayed response!  Was literally typing this message out when I saw your new comment.  Just want to add that once AT is done, you can merge the PR, but just be sure that your commit message follows the [proper format](https://github.com/medic/cht-conf#commit-format) since it may trigger a new release....

**Comment by jkuester** [comment]
@medic/quality-assurance just a note on testing:  the previous behavior is that the console would print an error whenever the instance link was not specified _even if an instance was not required for the given actions._ So, `compile-app-forms` does not connect to a CHT instance, but would still print the error (but would go on to perform the action anyway).  

The changes in `524-no-help-for-actions-without-instance` should just make it so that the error is only printed when actually relevant.
